#!/bin/bash
#
# Run a list of make targets in several directories at once.

tgtcmd=make
paths="renényffenegger aaa somenotes"

for F in $paths
do
	echo "-- Project: $F --"
	echo -n "> "; pushd $F

	$tgtcmd "$@"

	echo -n "> "; popd

	echo "-- -- --"
	echo ""
done
